server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers:  localhost:9092
      group-id: sm-group-1

kafka-topic:
  name: sm-test-topic-1
  partitions: 3
  replication-factor: 1

#spring:
#  kafka:
#    consumer:
#      bootstrap-servers:  localhost:9092
#      group-id: sm-group-1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages : com.kafkatech.dto
