server:
  port: 8081
  servlet:
    context-path: /consumer-app-v2

spring:
  kafka:
    consumer:
      bootstrap-servers:  localhost:9092
      group-id: sm-group-1
    topics:
      - name: sm-text-topic
      - name: sm-json-topic


#spring:
#  kafka:
#    consumer:
#      bootstrap-servers:  localhost:9092
#      group-id: sm-group-1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages : com.kafkatech.dto
